### ISSUE TITLE
Support cassandra driver 3.0

### ISSUE THREAD

**Issue by devshorts** [composable-systems/dropwizard-cassandra#17]
From what I can tell the only thing that isn't supported is the min/max connections in the pooling factory.   Those methods were renamed and the min one seems to have been removed completely.

Temporarily I subclasses pooling factory and created my own builder to work around this, but it would be good to have first class support of this

**Comment by stuartgunter** [comment]
I'm not sure about min connections, but I think the max connections are already supported through https://github.com/stuartgunter/dropwizard-cassandra/blob/master/src/main/java/org/stuartgunter/dropwizard/cassandra/pooling/HostDistanceOptions.java

The snippet from the README shows potential config options:

```yaml
poolingOptions:
  heartbeatInterval:
  poolTimeout:
  local:
    minSimultaneousRequests:
    maxSimultaneousRequests:
    coreConnections:
    maxConnections:
  remote:
    minSimultaneousRequests:
    maxSimultaneousRequests:
    coreConnections:
    maxConnections:
```

Are those the config options you're thinking of, or are there others that are missing? It'd be great if you could include a link to the JavaDocs showing which properties need to be set.

Thanks
